### ISSUE TITLE
Investment cap can be circumvented

### ISSUE THREAD

**Issue by janbro** [savedroid/contracts#1]
In the following lines, it seems there is a cap to the amount of wei a beneficiary who is not on the whitelist can purchase with, however, a beneficiary can separate their transaction into multiple transactions to circumvent this cap.
```
if (weiAmount >= minWeiWhitelistInvestment) {
        require(investorWhitelist[beneficiary]);
}
```
Suggested fix is to check the total amount an investor has sent is not over the specified cap.
```
if (investments[beneficiary].add(weiAmount) >= minWeiWhitelistInvestment) {
        require(investorWhitelist[beneficiary]);
}
```

**Comment by airbone42** [comment]
Hi @janbro,

thanks for this. We're looking into the issue and will come back to you shortly.

**Comment by matttk** [comment]
This issue won't be fixed, as they will not have a valid contract with us, according to the T&Cs they signed on the webpage.
