### ISSUE TITLE
Insufficient whale protection/max wei investment insufficient

### ISSUE THREAD

**Issue by janbro** [savedroid/contracts#2]
validPurchase() only checks if the current transactions value is below the maxWeiInvestment. A whale can send multiple transactions with a very high gas price and a value slightly below the maxWeiInvestment and front run other buyers.
Suggested fix: set a max gas price for buy transactions and compare the beneficiaries total investments against maxWeiInvestment.

**Comment by airbone42** [comment]
Hi @janbro,

thanks for this. We're looking into the issue and will come back to you shortly.

**Comment by matttk** [comment]
This issue won't be fixed, as they will not have a valid contract with us, according to the T&Cs they signed on the webpage.
